MINISTRIES = [
    "Atos do Poder Judiciário",
    "Atos do Poder Legislativo",
    "Atos do Poder Executivo",
    "Presidência da República",
    "Ministério da Agricultura e Pecuária",
    "Ministério da Ciência, Tecnologia e Inovação",
    "Ministério das Comunicações",
    "Ministério da Cultura",
    "Ministério da Defesa",
    "Ministério do Desenvolvimento Agrário e Agricultura Familiar",
    "Ministério do Desenvolvimento, Indústria, Comércio e Serviços",
    "Ministério dos Direitos Humanos e da Cidadania",
    "Ministério da Educação",
    "Ministério do Empreendedorismo, da Microempresa e da Empresa de Pequeno Porte",
    "Ministério do Esporte",
    "Ministério da Fazenda",
    "Ministério da Gestão e da Inovação em Serviços Públicos",
    "Ministério da Igualdade Racial",
    "Ministério da Integração e do Desenvolvimento Regional",
    "Ministério da Justiça e Segurança Pública",
    "Ministério de Minas e Energia",
    "Ministério da Pesca e Aquicultura",
    "Ministério de Portos e Aeroportos",
    "Ministério dos Povos Indígenas",
    "Ministério da Previdência Social",
    "Ministério das Relações Exteriores",
    "Ministério da Saúde",
    "Ministério do Trabalho e Emprego",
    "Ministério dos Transportes",
    "Banco Central do Brasil",
    "Ministério Público da União",
    "Poder Judiciário",
    "Entidades de Fiscalização do Exercício das Profissões Liberais",
]
